packages:
  - packages/*

patchedDependencies:
  load-tsconfig@0.2.5: patches/load-tsconfig@0.2.5.patch
  rollup-plugin-typescript2@0.32.1: patches/rollup-plugin-typescript2@0.32.1.patch

overrides:
  "vite-plugin-dts@1.7.3>@microsoft/api-extractor": 7.33.8
